### PR TITLE
Added the linter files and update the readme

### PR DESCRIPTION
**Pull request by Dmambo**
## FEATURE IMPLEMENTED

**Description**
Allows users to view a random greeting message generated from a Rails API. The following changes were made:

- A new Rails API app called 'hello-rails-back-end' was created with a Postgres database set up.
- A 'greetings' table was created in the Rails app to store 5 different greeting messages.
- An API endpoint was created in the Rails app that selects a random greeting message from the 'greetings' table.
- A new React app called 'hello-react-front-end' was created with react-router set up.
- A 'Greeting' component was created in the React app to display a random greeting message.
- An Axios was implemented in the React app to connect to the Rails API endpoint and fetch a random greeting message.
- The random greeting message is displayed in the 'Greeting' component.
- 

Checklist

- [x]  Related issue(s) have been linked
- [x]  Code follows project coding conventions and style guide
- [x] Link to the [BACKEND PULL REQUEST](https://github.com/Dmambo/hello-rails-back-end/pull/1)

### CODE REVIEW

**Review by brytebee — CHANGES_REQUESTED** [review]
Hi, @Dmambo 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request



You have submitted a project, that has no PR for the backend. Kindly create a PR for the backend project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by rloterh — COMMENTED** [review]
Hi Ibrahim, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that this project is submitted using the PR of the Rails API backend, not the React frontend; Moreover, the backend link you provided is inaccessible. Kindly change the viewing permission on that repo so that it's accessible to the public.

**Backend link inaccessible:**
image
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by TedLivist — COMMENTED** [review]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @Dmambo,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### Your backend link is not accessible. Perhaps the repo is set to private. Kindly fix that.

image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by emmanuellekamwa — APPROVED** [review]
**STATUS: APPROVED ✔👋🎉**
Hello @Dmambo 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Descriptive PR.
- Good commit messages.
- Good job implementing the project requirements.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
